services:
  # Backend Service
  - type: web
    name: be-todo
    env: docker
    plan: free
    dockerContext: todo-app/backend
    dockerfilePath: todo-app/backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000

  # Frontend Service
  - type: web
    name: fe-todo
    env: docker
    plan: free
    dockerContext: todo-app/frontend
    dockerfilePath: todo-app/frontend/Dockerfile
    envVars:
      - key: API_URL
        value: https://be-todo.onrender.com