services:
  # Backend Service
  - type: web
    name: be-todo
    env: docker
    plan: free
    dockerContext: todo-app/backend
    dockerfilePath: todo-app/backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d7tmtf9o3t8c739m6c80-a
      - key: DB_USER
        value: todo_db_57d9_user
      - key: DB_PASSWORD
        value: UWQB7cIk9ILagKc1fpqNkKwiyGhw19AP
      - key: DB_NAME
        value: todo_db_57d9
      - key: DB_PORT
        value: 54321
      - key: PORT
        value: 5000

  # Frontend Service
  - type: web
    name: fe-todo
    env: docker
    plan: free
    dockerContext: todo-app/frontend
    dockerfilePath: todo-app/frontend/Dockerfile
    envVars:
      - key: API_URL
        value:  https://be-todo-p95q.onrender.com